name = "nexus"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "NEXUS_DB"
database_name = "nexus-db"
database_id = "5055f9eb-ea3f-4991-b456-653e049cea49"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "NEXUS_KV"
id = "edc59fe4d4e140bcb2136a48443dc007"

[triggers]
crons = ["0 2 * * *", "*/5 * * * *"]

[vars]
ENVIRONMENT = "production"

[env.staging]
name = "nexus-staging"

[[env.staging.d1_databases]]
binding = "NEXUS_DB"
database_name = "nexus-db-staging"
database_id = "ce65e1b6-656e-4b3d-9c29-b1e2492b1a1e"
migrations_dir = "migrations"

[[env.staging.kv_namespaces]]
binding = "NEXUS_KV"
id = "1776216c1a7749759fcab713acf35e12"

[env.staging.vars]
ENVIRONMENT = "staging"
